update-users and delete-users
Motion-CodeHouse-Ltd/backend-kwaco pull request #18
Opened 2022-10-03 16:56 UTC by Gahamanyiced

What this PR do?
- Update a user info
- Delete a user

2022-10-03 19:09 UTC, ncutixavier requested changes

2022-10-03 19:51 UTC, TuyizeeAnastase commented on src/controllers/user.controller.js
> +        message: 'User updated successful!',
successfully

2022-10-03 19:51 UTC, TuyizeeAnastase commented on src/controllers/user.controller.js
> +      await deleteUsers(user.id);
change deleteUsers function to deleteUser

2022-10-03 19:51 UTC, TuyizeeAnastase commented on src/controllers/user.controller.js
> +  async deleteUser(req, res) {
change deleteUser to userDelete

2022-10-03 19:51 UTC, TuyizeeAnastase commented on src/controllers/user.controller.js
> +  async updateUser(req, res) {
change updateUser to userUpdate, it is confusing with other function at the bottom `await updateUser`

2022-10-06 09:04 UTC, TuyizeeAnastase approved these changes
Improve Pull request description and how to test 
refer to this https://github.com/Motion-CodeHouse-Ltd/backend-kwaco/pull/14

2022-10-06 09:06 UTC, merged